spring:
    datasource:
        driverClassName: org.postgresql.Driver
        initialSize: 5
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        removeAbandoned: true
    jpa:
        hibernate:
            ddl-auto: update
